#pragma once

static const void *jump_table[] = {
	&&TARGET_HALT,
	&&TARGET_POP,

	&&TARGET_CONST,
	&&TARGET_TRUE,
	&&TARGET_FALSE,
	&&TARGET_NULL,
	&&TARGET_LIST,
	&&TARGET_MAP,
	&&TARGET_CLOSURE,
	&&TARGET_CURRENT_CLOSURE,

	&&TARGET_ADD,
	&&TARGET_SUB,
	&&TARGET_MUL,
	&&TARGET_DIV,
	&&TARGET_MOD,

	&&TARGET_BW_AND,
	&&TARGET_BW_OR,
	&&TARGET_BW_XOR,
	&&TARGET_BW_NOT,
	&&TARGET_BW_LSHIFT,
	&&TARGET_BW_RSHIFT,

	&&TARGET_AND,
	&&TARGET_OR,
	&&TARGET_EQUAL,
	&&TARGET_NOT_EQUAL,
	&&TARGET_GREATER_THAN,
	&&TARGET_GREATER_THAN_EQUAL,

	&&TARGET_MINUS,
	&&TARGET_BANG,
	&&TARGET_INDEX,

	&&TARGET_CALL,
	&&TARGET_CONCURRENT_CALL,
	&&TARGET_RETURN,
	&&TARGET_RETURN_VALUE,

	&&TARGET_JUMP,
	&&TARGET_JUMP_NOT_TRUTHY,

	&&TARGET_DOT,
	&&TARGET_DEFINE,
	&&TARGET_GET_GLOBAL,
	&&TARGET_SET_GLOBAL,
	&&TARGET_GET_LOCAL,
	&&TARGET_SET_LOCAL,
	&&TARGET_GET_BUILTIN,
	&&TARGET_GET_FREE,
	&&TARGET_LOAD_MODULE,
	&&TARGET_INTERPOLATE,
};
